(function(){
'use strict';
function byId(id){return document.getElementById(id)}
function pad(n){return n<10?'0'+n:''+n}
function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function tomorrow(){var d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+1);return d}
function niceDate(d){var days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];var mons=['January','February','March','April','May','June','July','August','September','October','November','December'];return days[d.getDay()]+' '+d.getDate()+' '+mons[d.getMonth()]}
function parseJson(s,fallback){try{return s?JSON.parse(s):fallback}catch(e){return fallback}}
function cleanList(a){var r=[],i,v;if(!a)return r;for(i=0;i<a.length;i++){v=(''+(a[i]||'')).replace(/^\s+|\s+$/g,'');if(v)r.push(v)}return r}
function escapeHtml(s){return(''+s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function sameList(a,b){var i;if(!a||!b||a.length!==b.length)return false;for(i=0;i<a.length;i++)if(a[i]!==b[i])return false;return true}
var mealDefaults=['Spaghetti Bolognese','Tacos','Chicken Schnitzel','Homemade Pizza'];
var voterDefaults=['Indie','Lola','Gideon','Mum','Dad'];
var activeVoter='';
var SUPABASE_URL='https://jacijznifstuwxylgvth.supabase.co';
var SUPABASE_KEY='sb_publishable_ZAwZ-r4xVO63zWhvWBb40Q_0EvsVvKp';
var cloudBallot=null,cloudVotes={},cloudReady=false,cloudBusy=false,lastCloudError='';
function ballotKey(){return key(tomorrow())}
function optionsStorage(){return'dinner-options:'+ballotKey()}
function votesStorage(){return'dinner-votes:'+ballotKey()}
function votersStorage(){return'dinner-voters'}
function templateStorage(){return'dinner-options-template'}
function migrationStorage(){return'dinner-cloud-migrated:'+ballotKey()}
function localVoters(){var a=parseJson(localStorage.getItem(votersStorage()),voterDefaults);a=cleanList(a);return a.length?a:voterDefaults.slice(0)}
function localOptions(){var a=parseJson(localStorage.getItem(optionsStorage()),null);if(!a)a=parseJson(localStorage.getItem(templateStorage()),mealDefaults);a=cleanList(a);return a.length?a:mealDefaults.slice(0)}
function localVotesAsMeals(){var raw=parseJson(localStorage.getItem(votesStorage()),{})||{},opts=localOptions(),out={},k,v;for(k in raw){if(raw.hasOwnProperty(k)){v=raw[k];if(typeof v==='number'&&v>=0&&v<opts.length)out[k]=opts[v];else if(typeof v==='string')out[k]=v}}return out}
function getVoters(){var a=cloudReady&&cloudBallot?cleanList(cloudBallot.voters):localVoters();return a.length?a:voterDefaults.slice(0)}
function getOptions(){var a=cloudReady&&cloudBallot?cleanList(cloudBallot.options):localOptions();return a.length?a:mealDefaults.slice(0)}
function getVotes(){return cloudReady?cloudVotes:localVotesAsMeals()}
function cacheBallot(options,voters){localStorage.setItem(optionsStorage(),JSON.stringify(options));localStorage.setItem(templateStorage(),JSON.stringify(options));localStorage.setItem(votersStorage(),JSON.stringify(voters))}
function cacheVotes(){var opts=getOptions(),o={},k,idx;for(k in cloudVotes){if(cloudVotes.hasOwnProperty(k)){idx=opts.indexOf(cloudVotes[k]);if(idx>=0)o[k]=idx}}localStorage.setItem(votesStorage(),JSON.stringify(o))}
function api(method,path,body,cb,prefer){var x=new XMLHttpRequest();x.open(method,SUPABASE_URL+'/rest/v1/'+path,true);x.setRequestHeader('apikey',SUPABASE_KEY);if(body!==null&&body!==undefined)x.setRequestHeader('Content-Type','application/json');if(prefer)x.setRequestHeader('Prefer',prefer);x.onreadystatechange=function(){var data=null;if(x.readyState!==4)return;try{data=x.responseText?JSON.parse(x.responseText):null}catch(e){}if(x.status>=200&&x.status<300){lastCloudError='';cb(null,data)}else{lastCloudError='Cloud sync error';cb(new Error(lastCloudError),data)}};try{x.send(body===null||body===undefined?null:JSON.stringify(body))}catch(e){lastCloudError='Cloud sync unavailable';cb(e,null)}}
function saveCloudSetup(options,voters,clearVotes,cb){api('POST','dinner_ballots?on_conflict=vote_date',[{vote_date:ballotKey(),options:options,voters:voters,updated_at:new Date().toISOString()}],function(err){if(err){if(cb)cb(err);return}cloudBallot={vote_date:ballotKey(),options:options.slice(0),voters:voters.slice(0)};cloudReady=true;cacheBallot(options,voters);if(clearVotes){api('DELETE','dinner_votes?vote_date=eq.'+encodeURIComponent(ballotKey()),null,function(err2){if(!err2){cloudVotes={};localStorage.removeItem(votesStorage())}if(cb)cb(err2)},'return=minimal')}else if(cb)cb(null)},'resolution=merge-duplicates,return=minimal')}
function loadCloud(cb){if(cloudBusy){if(cb)cb(null);return}cloudBusy=true;api('GET','dinner_ballots?vote_date=eq.'+encodeURIComponent(ballotKey())+'&select=vote_date,options,voters',null,function(err,data){var row,explicit,explicitOpts,lv;if(err){cloudBusy=false;if(cb)cb(err);return}row=data&&data.length?data[0]:null;explicit=localStorage.getItem(optionsStorage());explicitOpts=explicit?cleanList(parseJson(explicit,[])):null;lv=localVoters();if(!row){saveCloudSetup(explicitOpts&&explicitOpts.length?explicitOpts:localOptions(),lv,false,function(err2){if(err2){cloudBusy=false;if(cb)cb(err2);return}localStorage.setItem(migrationStorage(),'1');loadCloudVotes(cb)});return}cloudBallot=row;cloudReady=true;cacheBallot(cleanList(row.options),cleanList(row.voters));if(explicitOpts&&explicitOpts.length&&!localStorage.getItem(migrationStorage())&&!sameList(explicitOpts,cleanList(row.options))){saveCloudSetup(explicitOpts,lv,true,function(err3){if(!err3)localStorage.setItem(migrationStorage(),'1');cloudBusy=false;if(cb)cb(err3);refreshOpenPanels()});return}localStorage.setItem(migrationStorage(),'1');loadCloudVotes(cb)})}
function loadCloudVotes(cb){api('GET','dinner_votes?vote_date=eq.'+encodeURIComponent(ballotKey())+'&select=voter,meal',null,function(err,data){var i;if(!err){cloudVotes={};for(i=0;i<(data||[]).length;i++)cloudVotes[data[i].voter]=data[i].meal;cacheVotes();cloudReady=true}cloudBusy=false;if(cb)cb(err);refreshOpenPanels()})}
function forkIcon(){return '<svg viewBox="0 0 24 24"><path d="M5 3v6a3 3 0 0 0 6 0V3M8 3v18M16 3v10h4V3c-3 0-4 4-4 7M20 13v8"/></svg>'}
function plateIcon(){return '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/></svg>'}
function create(tag,cls,html){var e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e}
function build(){var app=document.querySelector('.app');if(!app||byId('dinnerVoteLaunch'))return;var launch=create('button','dinnerVoteLaunch',forkIcon()+'<span><span>DINNER VOTE</span><span class="dvTiny">TOMORROW</span></span>');launch.id='dinnerVoteLaunch';launch.onclick=openVote;app.appendChild(launch);var vote=create('div','dvOverlay');vote.id='dvOverlay';vote.innerHTML='<div class="dvPanel"><div class="dvHead"><div class="dvTitleWrap"><div class="dvDinnerIcon">'+forkIcon()+'</div><div><div class="dvTitle">Tomorrow\'s Dinner</div><div class="dvSub" id="dvDate"></div></div></div><button class="dvClose" id="dvClose">×</button></div><div class="dvBody"><div class="dvSectionLabel">Who is voting?</div><div class="dvVoters" id="dvVoters"></div><div class="dvSectionLabel">Choose one meal</div><div class="dvMealList" id="dvMeals"></div><div class="dvStatus" id="dvStatus"></div><button class="dvSettingsBtn" id="dvSettingsOpen">Dinner vote settings</button></div></div>';app.appendChild(vote);var settings=create('div','dvOverlay');settings.id='dvSettings';settings.innerHTML='<div class="dvPanel dvsPanel"><div class="dvHead"><div class="dvTitleWrap"><div class="dvDinnerIcon">'+forkIcon()+'</div><div><div class="dvTitle">Family Settings</div><div class="dvSub">Dinner vote syncs between phone and fridge</div></div></div><button class="dvClose" id="dvsClose">×</button></div><div class="dvsBody"><div class="dvsBlock"><div class="dvsBlockTitle">Tomorrow\'s meal options</div><div class="dvsHelp" id="dvsDate"></div><div class="dvsInputs" id="dvsMeals"></div></div><div class="dvsBlock"><div class="dvsBlockTitle">Voters</div><div class="dvsHelp">One vote per name. Anyone can change their choice before dinner is decided.</div><div class="dvsInputs dvsVoters" id="dvsVoters"></div></div><div class="dvsActions"><button class="dvsAction primary" id="dvsSave">Save dinner setup</button><button class="dvsAction warn" id="dvsClearVotes">Clear tomorrow\'s votes</button><button class="dvsAction" id="dvsResetChores">Reset today\'s chores</button><button class="dvsAction" id="dvsOpenVote">Open dinner vote</button></div><div class="dvsSaved" id="dvsSaved">Saved ✓</div></div></div>';app.appendChild(settings);byId('dvClose').onclick=closeVote;byId('dvOverlay').onclick=function(e){if(e.target===this)closeVote()};byId('dvSettingsOpen').onclick=function(){closeVote();openSettings()};byId('dvsClose').onclick=closeSettings;byId('dvSettings').onclick=function(e){if(e.target===this)closeSettings()};byId('dvsOpenVote').onclick=function(){closeSettings();openVote()};byId('dvsSave').onclick=saveSettings;byId('dvsClearVotes').onclick=clearVotes;byId('dvsResetChores').onclick=function(){closeSettings();var m=byId('modal');if(m)m.style.display='flex'};var gear=byId('settings');if(gear)gear.onclick=openSettings;loadCloud(function(){});setInterval(function(){var s=byId('dvSettings');if(!(s&&s.className.indexOf('open')>=0))loadCloud(function(){})},5000)}
function openVote(){byId('dvDate').innerHTML=niceDate(tomorrow());renderVoters();renderMeals();byId('dvOverlay').className='dvOverlay open';loadCloud(function(){renderVoters();renderMeals()})}
function closeVote(){var e=byId('dvOverlay');if(e)e.className='dvOverlay'}
function renderVoters(){var host=byId('dvVoters'),vs=getVoters(),votes=getVotes(),i,b;if(!host)return;host.innerHTML='';if((!activeVoter||vs.indexOf(activeVoter)<0)&&vs.length)activeVoter=vs[0];for(i=0;i<vs.length;i++){b=create('button','dvVoter'+(vs[i]===activeVoter?' active':'')+(votes.hasOwnProperty(vs[i])?' voted':''),escapeHtml(vs[i]));b.setAttribute('data-voter',vs[i]);b.onclick=function(){activeVoter=this.getAttribute('data-voter');renderVoters();renderMeals()};host.appendChild(b)}}
function renderMeals(){var host=byId('dvMeals'),opts=getOptions(),votes=getVotes(),vs=getVoters(),counts=[],i,v,max=0,b,mine='';if(!host)return;for(i=0;i<opts.length;i++)counts[i]=0;for(i=0;i<vs.length;i++){v=votes[vs[i]];if(typeof v==='string'){var vi=opts.indexOf(v);if(vi>=0)counts[vi]++}}for(i=0;i<counts.length;i++)if(counts[i]>max)max=counts[i];if(activeVoter&&typeof votes[activeVoter]==='string')mine=votes[activeVoter];host.innerHTML='';for(i=0;i<opts.length;i++){b=create('button','dvMeal'+(max>0&&counts[i]===max?' leading':'')+(mine===opts[i]?' mine':''),'<span class="dvMealMark">'+plateIcon()+'</span><span><span class="dvMealName">'+escapeHtml(opts[i])+'</span><span class="dvMealHint">Tap to vote'+(mine===opts[i]?' • your choice':'')+'</span></span><span class="dvVotes"><span class="dvVoteNum">'+counts[i]+'</span><span class="dvVoteWord">vote'+(counts[i]===1?'':'s')+'</span></span>');b.setAttribute('data-meal',opts[i]);b.onclick=castVote;host.appendChild(b)}updateStatus(opts,counts,vs,votes,max)}
function castVote(){if(!activeVoter)return;var meal=this.getAttribute('data-meal'),old=cloudVotes[activeVoter];cloudVotes[activeVoter]=meal;cloudReady=true;cacheVotes();renderVoters();renderMeals();api('POST','dinner_votes?on_conflict=vote_date,voter',[{vote_date:ballotKey(),voter:activeVoter,meal:meal,updated_at:new Date().toISOString()}],function(err){if(err){if(old===undefined)delete cloudVotes[activeVoter];else cloudVotes[activeVoter]=old;renderVoters();renderMeals()}else loadCloud(function(){})},'resolution=merge-duplicates,return=minimal')}
function updateStatus(opts,counts,vs,votes,max){var n=0,i,leaders=[],s=byId('dvStatus');for(i=0;i<vs.length;i++)if(votes.hasOwnProperty(vs[i]))n++;for(i=0;i<counts.length;i++)if(max>0&&counts[i]===max)leaders.push(opts[i]);if(!s)return;if(lastCloudError)s.innerHTML='Using the last synced dinner data. It will retry automatically.';else if(n===0)s.innerHTML='Pick your name, then tap the meal you want.';else if(leaders.length===1)s.innerHTML='<strong>'+escapeHtml(leaders[0])+'</strong>&nbsp; is leading • '+n+' of '+vs.length+' voted';else s.innerHTML='Tie between <strong>'+escapeHtml(leaders.join(' / '))+'</strong> • '+n+' of '+vs.length+' voted'}
function openSettings(){var e=byId('dvSettings');if(e)e.className='dvOverlay open';if(cloudReady){populateSettings()}else{loadCloud(function(){populateSettings()})}}
function closeSettings(){var e=byId('dvSettings');if(e)e.className='dvOverlay'}
function populateSettings(){var opts=getOptions(),vs=getVoters(),mh=byId('dvsMeals'),vh=byId('dvsVoters'),i,input;if(!mh||!vh)return;byId('dvsDate').innerHTML='These choices are for '+niceDate(tomorrow())+'. Changes save to the phone and fridge.';mh.innerHTML='';for(i=0;i<5;i++){input=create('input','dvsInput');input.type='text';input.maxLength=42;input.placeholder='Meal option '+(i+1);input.value=opts[i]||'';mh.appendChild(input)}vh.innerHTML='';for(i=0;i<5;i++){input=create('input','dvsInput');input.type='text';input.maxLength=16;input.placeholder='Voter '+(i+1);input.value=vs[i]||'';vh.appendChild(input)}}
function saveSettings(){var meals=[],voters=[],els,i,oldOpts=getOptions();els=document.querySelectorAll('#dvsMeals .dvsInput');for(i=0;i<els.length;i++)meals.push(els[i].value);meals=cleanList(meals);if(!meals.length)meals=mealDefaults.slice(0);els=document.querySelectorAll('#dvsVoters .dvsInput');for(i=0;i<els.length;i++)voters.push(els[i].value);voters=cleanList(voters);if(!voters.length)voters=voterDefaults.slice(0);cacheBallot(meals,voters);flashSaved('Saving to phone + fridge');saveCloudSetup(meals,voters,!sameList(oldOpts,meals),function(err){if(err)flashSaved('Saved locally, cloud retrying');else{if(voters.indexOf(activeVoter)<0)activeVoter=voters[0]||'';flashSaved('Saved everywhere')}})}
function clearVotes(){api('DELETE','dinner_votes?vote_date=eq.'+encodeURIComponent(ballotKey()),null,function(err){if(err)flashSaved('Could not clear cloud votes yet');else{cloudVotes={};localStorage.removeItem(votesStorage());renderVoters();renderMeals();flashSaved('Tomorrow\'s votes cleared everywhere')}},'return=minimal')}
function refreshOpenPanels(){var v=byId('dvOverlay');if(v&&v.className.indexOf('open')>=0){renderVoters();renderMeals()}}
function flashSaved(msg){var e=byId('dvsSaved');if(!e)return;e.innerHTML=escapeHtml(msg)+' ✓';e.className='dvsSaved show';setTimeout(function(){e.className='dvsSaved'},1800)}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',build)}else{build()}
})();
