(function(){
'use strict';
function byId(id){return document.getElementById(id)}
function pad(n){return n<10?'0'+n:''+n}
function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function tomorrow(){var d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+1);return d}
function niceDate(d){var days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];var mons=['January','February','March','April','May','June','July','August','September','October','November','December'];return days[d.getDay()]+' '+d.getDate()+' '+mons[d.getMonth()]}
function parseJson(s,fallback){try{return s?JSON.parse(s):fallback}catch(e){return fallback}}
function cleanList(a){var r=[],i,v;for(i=0;i<a.length;i++){v=(''+(a[i]||'')).replace(/^\s+|\s+$/g,'');if(v)r.push(v)}return r}
function escapeHtml(s){return(''+s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
var mealDefaults=['Spaghetti Bolognese','Tacos','Chicken Schnitzel','Homemade Pizza'];
var voterDefaults=['Indie','Lola','Gideon','Mum','Dad'];
var activeVoter='';
function ballotKey(){return key(tomorrow())}
function optionsStorage(){return'dinner-options:'+ballotKey()}
function votesStorage(){return'dinner-votes:'+ballotKey()}
function votersStorage(){return'dinner-voters'}
function templateStorage(){return'dinner-options-template'}
function getVoters(){var a=parseJson(localStorage.getItem(votersStorage()),voterDefaults);a=cleanList(a);return a.length?a:voterDefaults.slice(0)}
function getOptions(){var a=parseJson(localStorage.getItem(optionsStorage()),null);if(!a){a=parseJson(localStorage.getItem(templateStorage()),mealDefaults)}a=cleanList(a);return a.length?a:mealDefaults.slice(0)}
function getVotes(){return parseJson(localStorage.getItem(votesStorage()),{})||{}}
function saveVotes(v){localStorage.setItem(votesStorage(),JSON.stringify(v))}
function forkIcon(){return '<svg viewBox="0 0 24 24"><path d="M5 3v6a3 3 0 0 0 6 0V3M8 3v18M16 3v10h4V3c-3 0-4 4-4 7M20 13v8"/></svg>'}
function plateIcon(){return '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/></svg>'}
function create(tag,cls,html){var e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e}
function build(){
 var app=document.querySelector('.app');if(!app||byId('dinnerVoteLaunch'))return;
 var launch=create('button','dinnerVoteLaunch',forkIcon()+'<span><span>DINNER VOTE</span><span class="dvTiny">TOMORROW</span></span>');launch.id='dinnerVoteLaunch';launch.onclick=openVote;app.appendChild(launch);
 var vote=create('div','dvOverlay');vote.id='dvOverlay';vote.innerHTML='<div class="dvPanel"><div class="dvHead"><div class="dvTitleWrap"><div class="dvDinnerIcon">'+forkIcon()+'</div><div><div class="dvTitle">Tomorrow\'s Dinner</div><div class="dvSub" id="dvDate"></div></div></div><button class="dvClose" id="dvClose">×</button></div><div class="dvBody"><div class="dvSectionLabel">Who is voting?</div><div class="dvVoters" id="dvVoters"></div><div class="dvSectionLabel">Choose one meal</div><div class="dvMealList" id="dvMeals"></div><div class="dvStatus" id="dvStatus"></div><button class="dvSettingsBtn" id="dvSettingsOpen">Dinner vote settings</button></div></div>';app.appendChild(vote);
 var settings=create('div','dvOverlay');settings.id='dvSettings';settings.innerHTML='<div class="dvPanel dvsPanel"><div class="dvHead"><div class="dvTitleWrap"><div class="dvDinnerIcon">'+forkIcon()+'</div><div><div class="dvTitle">Family Settings</div><div class="dvSub">Dinner vote + existing chore controls</div></div></div><button class="dvClose" id="dvsClose">×</button></div><div class="dvsBody"><div class="dvsBlock"><div class="dvsBlockTitle">Tomorrow\'s meal options</div><div class="dvsHelp" id="dvsDate"></div><div class="dvsInputs" id="dvsMeals"></div></div><div class="dvsBlock"><div class="dvsBlockTitle">Voters</div><div class="dvsHelp">One vote is stored for each name. A voter can change their vote before dinner is decided.</div><div class="dvsInputs dvsVoters" id="dvsVoters"></div></div><div class="dvsActions"><button class="dvsAction primary" id="dvsSave">Save dinner setup</button><button class="dvsAction warn" id="dvsClearVotes">Clear tomorrow\'s votes</button><button class="dvsAction" id="dvsResetChores">Reset today\'s chores</button><button class="dvsAction" id="dvsOpenVote">Open dinner vote</button></div><div class="dvsSaved" id="dvsSaved">Saved ✓</div></div></div>';app.appendChild(settings);
 byId('dvClose').onclick=closeVote;byId('dvOverlay').onclick=function(e){if(e.target===this)closeVote()};byId('dvSettingsOpen').onclick=function(){closeVote();openSettings()};byId('dvsClose').onclick=closeSettings;byId('dvSettings').onclick=function(e){if(e.target===this)closeSettings()};byId('dvsOpenVote').onclick=function(){closeSettings();openVote()};byId('dvsSave').onclick=saveSettings;byId('dvsClearVotes').onclick=clearVotes;byId('dvsResetChores').onclick=function(){closeSettings();var m=byId('modal');if(m)m.style.display='flex'};
 var gear=byId('settings');if(gear)gear.onclick=openSettings;
}
function openVote(){byId('dvDate').innerHTML=niceDate(tomorrow());renderVoters();renderMeals();byId('dvOverlay').className='dvOverlay open'}
function closeVote(){var e=byId('dvOverlay');if(e)e.className='dvOverlay'}
function renderVoters(){var host=byId('dvVoters'),vs=getVoters(),votes=getVotes(),i,b;if(!host)return;host.innerHTML='';if(!activeVoter&&vs.length)activeVoter=vs[0];for(i=0;i<vs.length;i++){b=create('button','dvVoter'+(vs[i]===activeVoter?' active':'')+(votes.hasOwnProperty(vs[i])?' voted':''),vs[i]);b.setAttribute('data-voter',vs[i]);b.onclick=function(){activeVoter=this.getAttribute('data-voter');renderVoters();renderMeals()};host.appendChild(b)}}
function renderMeals(){var host=byId('dvMeals'),opts=getOptions(),votes=getVotes(),vs=getVoters(),counts=[],i,v,max=0,b,mine=-1;if(!host)return;for(i=0;i<opts.length;i++)counts[i]=0;for(i=0;i<vs.length;i++){v=votes[vs[i]];if(typeof v==='number'&&v>=0&&v<opts.length)counts[v]++}for(i=0;i<counts.length;i++)if(counts[i]>max)max=counts[i];if(activeVoter&&typeof votes[activeVoter]==='number')mine=votes[activeVoter];host.innerHTML='';for(i=0;i<opts.length;i++){b=create('button','dvMeal'+(max>0&&counts[i]===max?' leading':'')+(mine===i?' mine':''),'<span class="dvMealMark">'+plateIcon()+'</span><span><span class="dvMealName">'+escapeHtml(opts[i])+'</span><span class="dvMealHint">Tap to vote'+(mine===i?' • your choice':'')+'</span></span><span class="dvVotes"><span class="dvVoteNum">'+counts[i]+'</span><span class="dvVoteWord">vote'+(counts[i]===1?'':'s')+'</span></span>');b.setAttribute('data-index',i);b.onclick=castVote;host.appendChild(b)}updateStatus(opts,counts,vs,votes,max)}
function castVote(){if(!activeVoter)return;var i=parseInt(this.getAttribute('data-index'),10),votes=getVotes();votes[activeVoter]=i;saveVotes(votes);renderVoters();renderMeals()}
function updateStatus(opts,counts,vs,votes,max){var n=0,i,leaders=[];for(i=0;i<vs.length;i++)if(votes.hasOwnProperty(vs[i]))n++;for(i=0;i<counts.length;i++)if(max>0&&counts[i]===max)leaders.push(opts[i]);var s=byId('dvStatus');if(!s)return;if(!opts.length)s.innerHTML='Dad needs to add tomorrow\'s meal choices in settings.';else if(n===0)s.innerHTML='Pick your name, then tap the meal you want.';else if(leaders.length===1)s.innerHTML='<strong>'+escapeHtml(leaders[0])+'</strong>&nbsp; is leading • '+n+' of '+vs.length+' voted';else s.innerHTML='Tie between <strong>'+escapeHtml(leaders.join(' / '))+'</strong> • '+n+' of '+vs.length+' voted'}
function openSettings(){populateSettings();var e=byId('dvSettings');if(e)e.className='dvOverlay open'}
function closeSettings(){var e=byId('dvSettings');if(e)e.className='dvOverlay'}
function populateSettings(){var opts=getOptions(),vs=getVoters(),mh=byId('dvsMeals'),vh=byId('dvsVoters'),i,input;byId('dvsDate').innerHTML='These choices are for '+niceDate(tomorrow())+'. Blank rows are ignored.';mh.innerHTML='';for(i=0;i<5;i++){input=create('input','dvsInput');input.type='text';input.maxLength=42;input.placeholder='Meal option '+(i+1);input.value=opts[i]||'';input.setAttribute('data-meal',i);mh.appendChild(input)}vh.innerHTML='';for(i=0;i<5;i++){input=create('input','dvsInput');input.type='text';input.maxLength=16;input.placeholder='Voter '+(i+1);input.value=vs[i]||'';input.setAttribute('data-voter',i);vh.appendChild(input)}}
function saveSettings(){var meals=[],voters=[],els,i,oldOpts=getOptions(),changed=false;els=document.querySelectorAll('#dvsMeals .dvsInput');for(i=0;i<els.length;i++)meals.push(els[i].value);meals=cleanList(meals);if(!meals.length)meals=mealDefaults.slice(0);els=document.querySelectorAll('#dvsVoters .dvsInput');for(i=0;i<els.length;i++)voters.push(els[i].value);voters=cleanList(voters);if(!voters.length)voters=voterDefaults.slice(0);if(oldOpts.length!==meals.length)changed=true;else for(i=0;i<meals.length;i++)if(oldOpts[i]!==meals[i]){changed=true;break}localStorage.setItem(optionsStorage(),JSON.stringify(meals));localStorage.setItem(templateStorage(),JSON.stringify(meals));localStorage.setItem(votersStorage(),JSON.stringify(voters));if(changed)localStorage.removeItem(votesStorage());if(voters.indexOf(activeVoter)<0)activeVoter=voters[0]||'';flashSaved(changed?'Saved • votes cleared because meals changed':'Saved')}
function clearVotes(){localStorage.removeItem(votesStorage());flashSaved('Tomorrow\'s votes cleared')}
function flashSaved(msg){var e=byId('dvsSaved');if(!e)return;e.innerHTML=msg+' ✓';e.className='dvsSaved show';setTimeout(function(){e.className='dvsSaved'},1600)}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',build)}else{build()}
})();
